### ISSUE TITLE
File "/usr/local/lib/python3.4/dist-packages/rplidar.py", line 187, in _read_descriptor     raise RPLidarException('Descriptor length mismatch') rplidar.RPLidarException: Descriptor length mismatch

### ISSUE THREAD

**Issue by krishnakumarmoorthy** [SkoltechRobotics/rplidar#18]

**Comment by TheEpicIronman** [comment]
By any chance, would you have the solution to this problem? Im using an RPLidar A3 and im getting this error on a linux board similar to a raspberry pi, its got much more processing power though.

**Comment by cdmsjtr** [comment]
Change the baudrate to 256000 in rplidar.py to support A3 @TheEpicIronman
